### ISSUE TITLE
Alternative way to set binnng of histogram 

### ISSUE THREAD

**Issue by minglho** [isle-project/isle-editor#1139]
# Use a cutpoint and a bin width

The x-axis would have much nicer scale if I can set how the histogram is binned by providing bin width and one of the cutpoints. For instance, for the Age variable in the [Heart Disease Data Explorer](https://isle.stat.cmu.edu/data-explorers/heartdisease/), seeing that Age ranges from 24 to 70, it is natural that I would want my histogram to have bin width of 5 with one of the cutpoints landing on a multiple of 5. Therefore, if I can enter 5 for bin width and 25 for one of the cutpoints to determine how the histogram is displayed, that would be very helpful.

# Toggle between left or right endpoint inclusion

In the above example, it would make more sense to have binning intervals include the right instead of left endpoint when the cutpoints are at multiples of 5. This would avoid having a right-most bar for the interval $[70, 75)$ in the histogram with a count of 3, while the bar for the interval $[65, 70)$ has a count that's over 100. The jump from 100 down to 3 distracts from the overall shape of the histogram.

**Comment by gweinberg** [comment]
^ upvote, nice suggestions.  The cutpoint/binwidth options are the way Minitab does it:  After you make a histogram, there's a popup control where you can put in user defined cutpoints (or midpoints if desired, you can toggle between cutpoint mode and midpoint mode), and user defined number of intervals.  [I like "number of intervals" instead of "bin width", too]

**Comment by jricoiii** [comment]
in working on developing my lessons, I too find that having an option to control the binwidth would be beneficial, since when only using number of bin is not possible to get a standard bin width (say in units of 5 and 10 )

**Comment by jspm-kymetis** [comment]
Suggestion - instead of just Choose # of bins -> Choose either # or bin width/size - one or the other, greys out the one not chosen.

**Comment by minglho** [comment]
> Suggestion - instead of just Choose # of bins -> Choose either # or bin width/size - one or the other, greys out the one not chosen.

When you choose bin size, you also need to be able to choose a cutpoint.

**Comment by Planeshifter** [comment]
It's now possible to specify either the number of bins or the bin width alongside start/end points for the bins, which should achieve the desired result.

Closing as the resolution of this issue is part of today's release. Please leave an additional comment in case the issue was not resolved properly and we will revisit the problem.
