### ISSUE TITLE
Data Points Not Included in Histogram

### ISSUE THREAD

**Issue by minglho** [isle-project/isle-editor#1140]
I use the variable Age in the [Heart Disease Data Explorer](https://isle.stat.cmu.edu/data-explorers/heartdisease/) to generate the following histograms using different number of bins.

## Using 10 bins:
The right-most bar has a count of 117. When you count the sorted Age column, those are 117 observations of ages 66-69. The 3 counts for age 70 are missing from the histogram.
![image](https://user-images.githubusercontent.com/13249661/87237446-3ee15480-c3ab-11ea-9821-46792acb77a9.png)

## Using 16 bins:
The right-most bar has a count of 43. When you count the sorted Age column, those are 43 observations of ages 68-69. The 3 counts for age 70 are missing from the histogram.
![image](https://user-images.githubusercontent.com/13249661/87237474-8c5dc180-c3ab-11ea-9efa-cd15bcd72ed9.png)

**Comment by Planeshifter** [comment]
I am not able to reproduce this bug. I see the following histograms for 10 and 16 bins, respectively:

![image](https://user-images.githubusercontent.com/1913638/88321056-8d1c1f00-ccec-11ea-94b9-13467c17e902.png)

Would you be able to please try to reproduce the error once more? I am curious what happens when you click the "Autoscale" option and whether for some reason the x-axis merely wasn't fully showed.
