### ISSUE TITLE
Annotation in Sketchpad Not Affixed in Place in PDF

### ISSUE THREAD

**Issue by minglho** [isle-project/isle-editor#1156]
Please see this [video](https://www.awesomescreenshot.com/video/411761?key=4096e78fdd5bea568add4e5b6af2a5ae) that demonstrates the problem when I loaded a PDF into it.

**Comment by Planeshifter** [comment]
Would you be able to please try the following: Hit the Return / Enter key after inserting some text on the rendered PDF. Is the annotation still not fixed in place after doing so?

In either case, the current behavior for inserting a text annotation is quite confusing as one doesn't realize that one has to hit Return / Enter for the annotation to be placed in the document / saved. On the TODO list to rethink how this should ideally work.

**Comment by Planeshifter** [comment]
The text insertion has meanwhile been refactored such that changing slides or selecting a different mode will trigger the text to be inserted. One still has to hit Return when staying in the text mode and trying to insert another text at a different position on the slide.
