### ISSUE TITLE
Number question embedded in table, configurator menu opens for paragraph element, not number question

### ISSUE THREAD

**Issue by sacole167** [isle-project/isle-editor#1284]
Number question embedded in a table. When you open the number question configurator menu, it open a configurator menu for a "paragraph element" instead.

<img width="1440" alt="Screen Shot 2020-08-31 at 2 13 50 PM" src="https://user-images.githubusercontent.com/69658229/91769540-7216b780-eb94-11ea-9d55-c12608e2f556.png">
<img width="1440" alt="Screen Shot 2020-08-31 at 2 12 57 PM" src="https://user-images.githubusercontent.com/69658229/91769545-73e07b00-eb94-11ea-8e1c-4f3ebab3daa9.png">

**Comment by Planeshifter** [comment]
Could you please let me know what version of the editor you are using (Help -> About)? 
I recognize this error from the past but it should have been fixed by version 0.63.1. If you are on the most recent version, it would be great if you could point to the uploaded lesson or send me the source code of the lesson.

**Comment by sacole167** [comment]
Yes. Updating the editor fixed the problem. Incidentally, I was on version 59. This morning it installed an automatic update, but apparently not all the way up on to 63.

**Comment by Planeshifter** [comment]
Glad to hear that the update fixed the problem! And thanks for reporting that the update process didn't update to the most recent version. I will be looking into that.
