### ISSUE TITLE
inconsistent bin indicator upon mouseover, for histograms grouped by

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#1515]
When mousing over a bar of a histogram in ISLE, a popup appears giving the frequency, and another popup appears below the X axis showing the midpoint of the bin.  

Part (a) of issue:  Request for the bin indicator to show the range of the bin, rather than the midpoint of the bin (or maybe, some toggle for the user to decide).

Part (b) of issue:  When making a histogram grouped by a grouping variable, the bin indicator is different for one group; it shows the bin range rather than the bin midpoint:

[this is from https://isle.stat.cmu.edu/36-200-fall20/worldcup_project2/  --> histogram of Shots Attempted, grouped by Position, mode=faceted (number of columns doesn't matter):

![image](https://user-images.githubusercontent.com/31780210/100822788-fa6d5880-3420-11eb-8525-6258d75dd009.png)

The same bug happens in overlay mode, in an even more confusing way because in overlay mode when you mouse over, for the one group that shows the bin range instead of bin midpoint, the range appears inside the same popup as the frequency:

![image](https://user-images.githubusercontent.com/31780210/100823119-9eef9a80-3421-11eb-839b-4bde0e30c9e4.png)

**Comment by Planeshifter** [comment]
So after looking into this, seems the different in display is not a bug but expected behavior of Plotly.js we cannot easily change.

![image](https://user-images.githubusercontent.com/1913638/127942777-8e5435e7-7b72-4550-af55-9ed52289ca14.png)

In above plot, I toggled off the bars for any position aside from "Defender" and "Forward". When hovering the mouse over 0 on the x-axis, the orange tooltip displays `81` since this is the count for the orange bin that contains just observations with the value zero. In contrast, the green bin spans the values 0 to 1, in which `47` observations fall.

One alternative we have is to display a unified hover menu containing information for the all bars at the respective x position as follows:
![image](https://user-images.githubusercontent.com/1913638/127943420-522d0970-c0e4-4f3d-bbf9-88471b540a95.png)

But again, we see that the green bar has a range displayed whereas for all the other categories a range is omitted since only the value `0` is included in the respective bins.

**Comment by gweinberg** [comment]
interesting, so the apparent oddness was unique to that dataset (and to the default bin ranges).
