### ISSUE TITLE
Have a "camera" button option for tables.

### ISSUE THREAD

**Issue by sastoudt** [isle-project/isle-editor#2323]
### Problem

It would be helpful if students could download a PNG version of the tables they create (like they can do for plots). When I use the "drag plot" feature to try to move a table over to a Google Doc for instance, the formatting doesn't transfer over.

### Solution

Some way to capture table output that doesn't require a manual screenshot.

### Additional context

None.

**Comment by Planeshifter** [comment]
Hmm, it is possible to move a table over to a Google Doc and have it inserted there as a table by clicking on the "Drag Plot" button instead of dragging and then using Ctrl+V to insert the table there, see e.g. below for how it looks like for me:

![table](https://user-images.githubusercontent.com/1913638/131336536-06470690-1cc3-47f6-842f-0e705fa4893c.png)

Not sure why formatting is lost when dragging. WIll investigate.

**Comment by sastoudt** [comment]
Oh, not a huge deal, I wasn't aware of the click on Drag Plot and then Control + V approach, that works!

**Comment by Planeshifter** [comment]
With the next editor update, drag & drop for tables and model outputs will correctly insert them as table into e.g. Google Docs. Thanks for bringing this to my attention!
