### ISSUE TITLE
upload lesson -> select course should default to most recent course uploaded to

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2378]
### Problem

Currently, **upload lesson -> select course** seems to default to whatever course the lesson had *originally* belonged to (even if it that is many semesters ago).  This is not the typical use case for instructors, and it constantly causes me to export to the wrong semester.

So, a two part enhancement:
1) "select course" should default to whatever course that user has most recently uploaded to.  That would seem to be the most common use case for an instructor, since they will most likely be uploading to the same course all semester.
2) If attempting to upload to a course past its end date, the editor should pop up a warning, like:  "You are attempting to upload to a course past its end date.  Do you want to proceed?  [continue] [abort]."  (That way, unintentional export attempts to wrong prior semesters will be caught.)

### Solution

see above.

### Additional context

None.

**Comment by Planeshifter** [comment]
Thanks for these suggestions!

The behavior will be changed in the next editor as follows:

- The last selected course of the user will be saved and restored in the select box when opening the "Export Lesson" page, even after exiting the editor
- If no course has been selected yet, the most recently created one instead of the oldest one will be pre-selected in the select box

While I can see suggestion 2) having some usefulness, it's not feasible to implement given a course has no start / end date but rather its associated cohorts. We could consider adding an option to set courses to "inactive" or something like that. Closing this issue for now but we can revisit in case the above changes are not sufficient in improving the upload process and accidentally uploading to old courses remains a problem.
