### ISSUE TITLE
mathjax equivalent of \widebar{} ?

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2696]
### Problem

I want the equivalent of $\widebar{X}$, but "widebar" isn't a mathjax function.  Any recommendations?

With $\bar{X}$ it's not as wide as I would like:
![image](https://user-images.githubusercontent.com/31780210/158229701-3fba726a-0596-41d6-aa0e-1846e1b4c197.png)

With $\overline{X}$ it's too thin and doesn't adjust for italics of the letter:
![image](https://user-images.githubusercontent.com/31780210/158229985-ace1de1d-4823-460f-9f23-f8a770a0edb1.png)

### Solution

would like the equivalent of \widebar

### Additional context

None.

**Comment by Planeshifter** [comment]
Looks like one may try using something like

```tex
$\overline{\!X}$
```

The `\!` will insert a negative thin space, effectively removing horizontal space used up by the letter.

**Comment by gweinberg** [comment]
ah true.  It's still too long and thin though

**Comment by Planeshifter** [comment]
Added a macro so that `\widebar` may be used in LaTeX equations now. However, due to lack of built-in support for `\widebar` in MathJax, it uses `\overline{\!X}` behind the scenes. Hence, it won't have the desired appearance. Better than nothing though as we could smoothly transition should a `\widebar` command become available in MathJax in the future via an extension.
