### ISSUE TITLE
request "restore original dataset" button also above spreadsheet

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2747]
### Problem

Thanks for moving the "create filtered dataset" to the top of the spreadsheet.  But the "restore original dataset" button will need to also be moved to the top, for consistency (otherwise students won't know to look for it)

### Solution

"restore original dataset" should appear above spreadsheet

### Additional context

None.

**Comment by Planeshifter** [comment]
This was an intentional decision, but I am open to ideas. Recall that the "Restore original dataset" button comes with the list of currently applied filters, which can alternatively removed on an individual basis. For example,

<img width="572" alt="image" src="https://user-images.githubusercontent.com/1913638/168662662-dcea50c0-f777-4f5d-b32c-f621ccb50d46.png">

Placing the button and list of filters above the data table will cause the table to be pushed down the more filters there are. With two or more filters, having the list of filters and the "Restore" button above the data table was already quite inconvenient as being able to see the observations without having to scroll is much more valuable when looking at the output panel or creating a new output via the toolbox. 

We could have it above and then maybe have the list of applied filters in a collapsible panel so that they are not visible by default (although I am not too fond of this solution as we then need to worry about people missing the list of filters altogether). Another potential solution would be to have the "Restore original dataset" button both at the top and at the bottom: Standing alone at the top, but then with the list of filters below the data table. Any other ideas?

**Comment by gweinberg** [comment]
Ah I see the problem.  
Another solution, above the spreadsheet a note to the effect of, "To restore original dataset, click the button below the spreadsheet."

**Comment by gweinberg** [comment]
The more I try it, the more I think there definitely needs to be something that appears above the spreadsheet once a filter is applied, because the user doesn't know to look below the spreadsheet, and if nothing appears, it seems like "create filtered dataset" didn't do anything.  How about putting it at the top, and having the cascade of filters in an expandable button, collapsed by default:
![image](https://user-images.githubusercontent.com/31780210/168904271-35d4ebb0-6c14-4722-8d62-6b8354b80119.png)

**Comment by Planeshifter** [comment]
The active filters are now displayed at the top (and collapsible).

**Comment by gweinberg** [comment]
**"The active filters are now displayed at the top (and collapsible)"**
Has this been implemented yet?  Because as of editor version 76.15, the "restore original dataset" button is still only below the spreadsheet, not above.

**Comment by Planeshifter** [comment]
Yes, starting with v0.76.16. Should look something like this:

<img width="562" alt="image" src="https://user-images.githubusercontent.com/1913638/173900230-5bcddb79-a966-4f60-afb8-29befb9c09d9.png">

**Comment by gweinberg** [comment]
Cool, when's the new release?

**Comment by gweinberg** [comment]
Thanks, installing
