### ISSUE TITLE
ability to edit text of "open dataset description" button in data explorers

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#2765]
### Problem

not sure if this is curently possible, but I'd like the ability to custom edit the text that appears on the "open dataset description" button, to say "study description" or something like that, because every semester there are students who never know/remember that you can click on it, and I get emails asking what the study description is.

### Solution

feature in editor to edit text on "open dataset" button.

### Additional context

None.

**Comment by gweinberg** [comment]
Yes combining the two into one document would be a good solution (and then change the text "variables description" to something like,  "description of study and variables")

**Comment by Planeshifter** [comment]
Refactored so that there is now one button to display dataset and variable descriptions, with the header being not clickable anymore. Using "dataset" instead of "study" since we need a general term that works for all kinds of datasets. Closing this issue as we hopefully don't need a way to customize the button label anymore (which would cause other issues given that the vertical width of the button would then be highly variable and we don't have that much vertical real estate in the first place). We can revisit this later if needed.
